# Site settings
author: Samantha Brake
title: Sammy Codes
header-img: img/home-bg.png
email: sammy.brake@gmail.com
copyright_name: Samantha Brake
description: > # this means to ignore newlines until "baseurl:"
  Flatiron Student Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  sammy-brake

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
